### ISSUE TITLE
can't start server after npm install

### ISSUE THREAD

**Issue by asuna** [Pillar1989/wifidog-server#1]
Hi,
I can't start server after npm install, could you tell me how to solve this?
details below.

**npm start error**
````bash
root@localubuntu:~/wifidog-server# npm start

> wifidog-server@0.0.0 start /root/wifidog-server
> nodejs ./bin/www

sh: 1: nodejs: not found

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! wifidog-server@0.0.0 start: `nodejs ./bin/www`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the wifidog-server@0.0.0 start script 'nodejs ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wifidog-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodejs ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wifidog-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wifidog-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/wifidog-server/npm-debug.log
````

**npm-debug.log**
````bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node',
1 verbose cli   '/usr/local/node/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wifidog-server@0.0.0~prestart: wifidog-server@0.0.0
6 silly lifecycle wifidog-server@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle wifidog-server@0.0.0~start: wifidog-server@0.0.0
8 verbose lifecycle wifidog-server@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle wifidog-server@0.0.0~start: PATH: /usr/local/node/lib/node_modules/npm/bin/node-gyp-bin:/root/wifidog-server/node_modules/.bin:/usr/local/node/bin:/usr/local/jdk/bin:/usr/local/node/bin:/usr/local/jdk/bin:/usr/local/node/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin
10 verbose lifecycle wifidog-server@0.0.0~start: CWD: /root/wifidog-server
11 silly lifecycle wifidog-server@0.0.0~start: Args: [ '-c', 'nodejs ./bin/www' ]
12 info lifecycle wifidog-server@0.0.0~start: Failed to exec start script
13 verbose stack Error: wifidog-server@0.0.0 start: `nodejs ./bin/www`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:100:13)
13 verbose stack     at ChildProcess.emit (events.js:185:7)
13 verbose stack     at maybeClose (internal/child_process.js:850:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
14 verbose pkgid wifidog-server@0.0.0
15 verbose cwd /root/wifidog-server
16 error Linux 4.2.0-27-generic
17 error argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "start"
18 error node v5.10.1
19 error npm  v3.8.3
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error wifidog-server@0.0.0 start: `nodejs ./bin/www`
24 error spawn ENOENT
25 error Failed at the wifidog-server@0.0.0 start script 'nodejs ./bin/www'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the wifidog-server package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     nodejs ./bin/www
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs wifidog-server
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls wifidog-server
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]
````

**Comment by Pillar1989** [comment]
You can modify https://github.com/Pillar1989/wifidog-server/blob/BBGW/package.json
"start": "nodejs ./bin/www"  -----> "start": "node ./bin/www"

**Comment by asuna** [comment]
Thx for reply, but still not work.
**npm start error**
````bash
root@localubuntu:~/wifidog-server# npm start

> wifidog-server@0.0.0 start /root/wifidog-server
> node ./bin/www

/root/wifidog-server/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /root/wifidog-server/node_modules/ref/build/binding.node
 → /root/wifidog-server/node_modules/ref/build/Debug/binding.node
 → /root/wifidog-server/node_modules/ref/build/Release/binding.node
 → /root/wifidog-server/node_modules/ref/out/Debug/binding.node
 → /root/wifidog-server/node_modules/ref/Debug/binding.node
 → /root/wifidog-server/node_modules/ref/out/Release/binding.node
 → /root/wifidog-server/node_modules/ref/Release/binding.node
 → /root/wifidog-server/node_modules/ref/build/default/binding.node
 → /root/wifidog-server/node_modules/ref/compiled/5.10.1/linux/x64/binding.node
    at bindings (/root/wifidog-server/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/root/wifidog-server/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/root/wifidog-server/node_modules/ffi/lib/ffi.js:6:11)
    at Module._compile (module.js:413:34)

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! wifidog-server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wifidog-server@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wifidog-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wifidog-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wifidog-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/wifidog-server/npm-debug.log
root@localubuntu:~/wifidog-server# rm -f npm-debug.log 
root@localubuntu:~/wifidog-server# clear
root@localubuntu:~/wifidog-server# npm start

> wifidog-server@0.0.0 start /root/wifidog-server
> node ./bin/www

/root/wifidog-server/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /root/wifidog-server/node_modules/ref/build/binding.node
 → /root/wifidog-server/node_modules/ref/build/Debug/binding.node
 → /root/wifidog-server/node_modules/ref/build/Release/binding.node
 → /root/wifidog-server/node_modules/ref/out/Debug/binding.node
 → /root/wifidog-server/node_modules/ref/Debug/binding.node
 → /root/wifidog-server/node_modules/ref/out/Release/binding.node
 → /root/wifidog-server/node_modules/ref/Release/binding.node
 → /root/wifidog-server/node_modules/ref/build/default/binding.node
 → /root/wifidog-server/node_modules/ref/compiled/5.10.1/linux/x64/binding.node
    at bindings (/root/wifidog-server/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/root/wifidog-server/node_modules/ref/lib/ref.js:5:47)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/root/wifidog-server/node_modules/ffi/lib/ffi.js:6:11)
    at Module._compile (module.js:413:34)

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! wifidog-server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wifidog-server@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wifidog-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wifidog-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wifidog-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/wifidog-server/npm-debug.log
````

**npm-debug.log**
````bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node',
1 verbose cli   '/usr/local/node/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle wifidog-server@0.0.0~prestart: wifidog-server@0.0.0
6 silly lifecycle wifidog-server@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle wifidog-server@0.0.0~start: wifidog-server@0.0.0
8 verbose lifecycle wifidog-server@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle wifidog-server@0.0.0~start: PATH: /usr/local/node/lib/node_modules/npm/bin/node-gyp-bin:/root/wifidog-server/node_modules/.bin:/usr/local/node/bin:/usr/local/jdk/bin:/usr/local/node/bin:/usr/local/jdk/bin:/usr/local/node/bin:/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin
10 verbose lifecycle wifidog-server@0.0.0~start: CWD: /root/wifidog-server
11 silly lifecycle wifidog-server@0.0.0~start: Args: [ '-c', 'node ./bin/www' ]
12 silly lifecycle wifidog-server@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle wifidog-server@0.0.0~start: Failed to exec start script
14 verbose stack Error: wifidog-server@0.0.0 start: `node ./bin/www`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid wifidog-server@0.0.0
16 verbose cwd /root/wifidog-server
17 error Linux 4.2.0-27-generic
18 error argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "start"
19 error node v5.10.1
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error wifidog-server@0.0.0 start: `node ./bin/www`
22 error Exit status 1
23 error Failed at the wifidog-server@0.0.0 start script 'node ./bin/www'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the wifidog-server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./bin/www
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs wifidog-server
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls wifidog-server
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`````

**Comment by Pillar1989** [comment]
It seems bindings version error. We use node version v0.12.13. wifidog-server works on beaglebone. We didnt test other platform.

**Comment by asuna** [comment]
I change version to v0.12.13 and still not work, any other solution?

**npm-debug.log**
````bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node',
1 verbose cli   '/usr/local/node/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v0.12.13
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart wifidog-server@0.0.0
6 info start wifidog-server@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info wifidog-server@0.0.0 Failed to exec start script
9 verbose stack Error: wifidog-server@0.0.0 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1019:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
10 verbose pkgid wifidog-server@0.0.0
11 verbose cwd /root/wifidog-server
12 error Linux 4.2.0-27-generic
13 error argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "start"
14 error node v0.12.13
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error wifidog-server@0.0.0 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the wifidog-server@0.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the wifidog-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs wifidog-server
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls wifidog-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
````

**Comment by Pillar1989** [comment]
You need install following package manually.
npm install ffi
npm install ref
npm install bindings

**Comment by asuna** [comment]
Thanks for your patience!
Installed manually and another error.

````bash
root@localubuntu:~/wifidog-server# npm start

> wifidog-server@0.0.0 start /root/wifidog-server
> node ./bin/www

info: Opening port 80 to serve up /var/lib/cloud9
info: startWifiDog
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn wdctl ENOENT
  at exports._errnoException (util.js:746:11)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:32)
  at child_process.js:1151:20
  at process._tickCallback (node.js:355:11)
  at Function.Module.runMain (module.js:503:11)
  at startup (node.js:129:16)
  at node.js:814:3


npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "start"
npm ERR! node v0.12.13
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! wifidog-server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wifidog-server@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the wifidog-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wifidog-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls wifidog-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/wifidog-server/npm-debug.log


root@localubuntu:~/wifidog-server# cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/node/bin/node',
1 verbose cli   '/usr/local/node/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v0.12.13
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart wifidog-server@0.0.0
6 info start wifidog-server@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info wifidog-server@0.0.0 Failed to exec start script
9 verbose stack Error: wifidog-server@0.0.0 start: `node ./bin/www`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/node/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1019:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
10 verbose pkgid wifidog-server@0.0.0
11 verbose cwd /root/wifidog-server
12 error Linux 4.2.0-27-generic
13 error argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "start"
14 error node v0.12.13
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error wifidog-server@0.0.0 start: `node ./bin/www`
17 error Exit status 1
18 error Failed at the wifidog-server@0.0.0 start script 'node ./bin/www'.
18 error This is most likely a problem with the wifidog-server package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node ./bin/www
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs wifidog-server
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls wifidog-server
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
````

**Comment by Pillar1989** [comment]
Because you didt install wifidog and config the whole environment. Please read readme.

**Comment by asuna** [comment]
Ok, thx.
